#!/usr/bin/env bash
set -euo pipefail

config=${1:?usage: check-config.sh CONFIG}
required=(
	CONFIG_64BIT CONFIG_X86_64 CONFIG_SMP CONFIG_HOTPLUG_CPU CONFIG_RELOCATABLE
	CONFIG_PCI CONFIG_SPARSEMEM CONFIG_MEMORY_HOTPLUG CONFIG_MEMORY_HOTREMOVE
	CONFIG_GENERIC_ALLOCATOR CONFIG_X86_MCE
	CONFIG_PRINTK CONFIG_TTY CONFIG_SERIAL_8250 CONFIG_SERIAL_8250_CONSOLE
	CONFIG_BLK_DEV_INITRD CONFIG_RD_GZIP CONFIG_BINFMT_ELF CONFIG_BINFMT_SCRIPT
	CONFIG_DEVTMPFS CONFIG_DEVTMPFS_MOUNT CONFIG_PROC_FS CONFIG_SYSFS CONFIG_TMPFS
	CONFIG_KEXEC CONFIG_KEXEC_FILE CONFIG_KEXEC_HANDOVER
	CONFIG_KEXEC_HANDOVER_ENABLE_DEFAULT CONFIG_MULTIKERNEL CONFIG_MKTTY
)

for symbol in "${required[@]}"; do
	grep -qx "${symbol}=y" "${config}" || {
		printf 'config check: required %s=y is missing\n' "${symbol}" >&2
		exit 1
	}
done

printf 'MK_CONFIG_OK required_symbols=%d\n' "${#required[@]}"
