#!/usr/bin/env bash
set -euo pipefail

config=${1:?usage: check-config.sh CONFIG}
required=(
	CONFIG_64BIT CONFIG_X86_64 CONFIG_SMP CONFIG_HOTPLUG_CPU CONFIG_RELOCATABLE
	CONFIG_PCI CONFIG_PCI_MSI CONFIG_PCI_IOV
	CONFIG_HYPERVISOR_GUEST CONFIG_PARAVIRT CONFIG_KVM_GUEST
	CONFIG_SPARSEMEM CONFIG_MEMORY_HOTPLUG CONFIG_MEMORY_HOTREMOVE
	CONFIG_GENERIC_ALLOCATOR CONFIG_X86_MCE
	CONFIG_PRINTK CONFIG_TTY CONFIG_SERIAL_8250 CONFIG_SERIAL_8250_CONSOLE
	CONFIG_BLK_DEV_INITRD CONFIG_RD_GZIP CONFIG_BINFMT_ELF CONFIG_BINFMT_SCRIPT
	CONFIG_DEVTMPFS CONFIG_DEVTMPFS_MOUNT CONFIG_PROC_FS CONFIG_SYSFS CONFIG_TMPFS
	CONFIG_BLOCK CONFIG_BLK_DEV CONFIG_SCSI CONFIG_BLK_DEV_SD CONFIG_SCSI_VIRTIO
	CONFIG_ATA CONFIG_SATA_AHCI CONFIG_ATA_PIIX CONFIG_EXT4_FS
	CONFIG_NET CONFIG_NETDEVICES CONFIG_INET CONFIG_PACKET CONFIG_UNIX
	CONFIG_IP_PNP CONFIG_IP_PNP_DHCP CONFIG_E1000 CONFIG_E1000E CONFIG_IGB CONFIG_IGBVF
	CONFIG_8139TOO
	CONFIG_VIRTIO CONFIG_VIRTIO_PCI CONFIG_VIRTIO_BLK CONFIG_VIRTIO_NET
	CONFIG_VIRTIO_CONSOLE CONFIG_FW_CFG_SYSFS CONFIG_NET_9P_VIRTIO CONFIG_9P_FS
	CONFIG_KEXEC CONFIG_KEXEC_FILE CONFIG_KEXEC_HANDOVER
	CONFIG_KEXEC_HANDOVER_ENABLE_DEFAULT CONFIG_MULTIKERNEL CONFIG_MKTTY CONFIG_MODULES
)

for symbol in "${required[@]}"; do
	grep -qx "${symbol}=y" "${config}" || {
		printf 'config check: required %s=y is missing\n' "${symbol}" >&2
		exit 1
	}
done

printf 'MK_CONFIG_OK required_symbols=%d\n' "${#required[@]}"
